services:
  psql_bp:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    # image: postgis/postgis:15-3.5
    # image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_postgis_v3_volume_bp:/var/lib/postgresql/data
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=pg_cron",
        "-c",
        "cron.database_name=${BLUEPRINT_DB_DATABASE}",
      ]

volumes:
  psql_postgis_v3_volume_bp:
  psql_postgis_v2_volume_bp:
  psql_postgis_volume_bp:
  psql_volume_bp:
